announcement: "🏆 Home of your 2026 State Champs!"
email: sabrerobotics6045@gmail.com
team_site: https://frc6045.com
socials:
  - label: Facebook
    url: https://www.facebook.com/SabreRobotics/
  - label: TikTok
    url: https://www.tiktok.com/@frc6045
  - label: Instagram
    url: https://www.instagram.com/6045_sabre_robotics/
